
import SideBarView from "@/components/sidebar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex-col">
         <SideBarView/>
          <div className="h-screen ml-0 md:ml-52 pt-12">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
